### PR TITLE
Update repository and build PyChooch for Python 3

### PR DESCRIPTION
**Pull request by beenje**
- Sync repo with version 5.0.9 using https://github.com/fadnywg/chooch/tree/d472b85202e8b30103cb8b72accc97d09e2063f6
- Fix PyChooch for new version (add some missing variables)
- Fix PyChooch for Python 3 (Py_InitModule was for Python 2)
- Add CMakeLists.txt to build chooch binary
- Update setup.py to replace `distutils` with `setuptools`
- Replace the `include <plplot.h>` with `<plplot/plplot.h>` to avoid having to add some specific include directories
- fixed Python Exception handling in case of gsl error

### CODE REVIEW

**Comment by meguiraun** [comment]
@marcus-oscarsson , @beteva , do you use pychooch? Is this ok to merge?

**Comment by beteva** [comment]
Thanks for the effort porting this to python3. I did not have the time and the courage. For me it is OK to merge.

> @marcus-oscarsson , @beteva , do you use pychooch? Is this ok to merge?

We do use chooch, but we do not use this repository any more. Chooch is part of the ccp4 package and we simply launch with subprocess to run it and get the result from the output file.  Please, have a look at [ESRFEnergyScan.py](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/HardwareObjects/ESRF/ESRFEnergyScan.py) HO.

**Comment by marcus-oscarsson** [comment]
Thanks !

**Comment by beenje** [comment]
@marcus-oscarsson thanks for merging!
Could you please tag the repo? I used 5.0.9 as `pychooch` version as it's the `chooch` version that is hard-coded in the `Makefile` and `copyright.c` files. I thought it made sense to use the same version as most files are from the `chooch` repo.

After that, I will try to publish a recipe to conda-forge.

@meguiraun tagged, thanks!

**Pull request merged**
